Feature/login
wecode-bootcamp-korea/28-1st-KurlyFlower-backend pull request #4
Opened 2021-12-30 08:11 UTC by evnif11

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-  로그인 api 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 데이터 처리
- 존재하지 않는 username일 경우 DoesNotExist 예외처리
- 보안을 위해 아이디 혹은 패스워드 틀렸을 경우 에러 메세지 따로 구분하지 않고 Invalid user 하나로 예외처리
- bcrypt를 활용해 패스워드 체크
- 로그인 성공시에 jwt 토큰 발행

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- except 구문의 순서가 중요하다면 코드 흐름 순서상으로 기재하면 될까요?

2021-12-30 10:11 UTC, jamessoun93 requested changes

2021-12-30 10:11 UTC, jamessoun93 commented on kurlyflower/urls.py
> +    path("users", include('users.urls')),
따옴표 팀내에서 정해서 통일해주세요!

2021-12-30 10:11 UTC, jamessoun93 commented on users/views.py
> +            user = User.objects.filter(username=username).first()
해당 username 을 가진 user 데이터는 하나밖에 없으니 get() 으로 처리한 뒤 없으면 exception 처리해주는 방식이 더 좋겠네요.

2021-12-30 10:11 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({"access_token":access_token}, status=200)
```suggestion
            payload = {
                "id"  : user.id,
                "exp" : datetime.now()+timedelta(hours=3),
                "iat" : datetime.now()
            }
            access_token = jwt.encode(payload, SECRET_KEY, ALGORITHM)
            
            return JsonResponse({"access_token": access_token}, status=200)
```

2021-12-30 10:11 UTC, jamessoun93 commented on users/views.py
> +
해당 exception 이 발생할 수 있는 코드였을까요? 🤔

2021-12-30 11:49 UTC, evnif11 commented on users/views.py
> +
유저가 존재하는 지 확인하는 User.objects.filter(username=username).exist() 대신에 한줄로 쓴건데 제가 틀린걸까요? 이해가 잘 안되서요

2021-12-31 05:14 UTC, jamessoun93 approved these changes, later dismissed

2021-12-31 05:15 UTC, jamessoun93 approved these changes

2021-12-31 05:15 UTC, merged

2021-12-31 05:16 UTC, jamessoun93 commented
LGTM