회원가입 기능 구현
wecode-bootcamp-korea/28-1st-KurlyFlower-backend pull request #5
Opened 2021-12-30 10:13 UTC by black2code

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

회원가입 데이터 처리
- 조건문과 정규식을 이용한 username, email, password 중복 및 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
- bcrypt 이용하여 패스워드 암호화

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 실제 홈페이지의 중복체크 버튼에 대한 키값이 하나만 들어왔을 경우, 해당 기능에 대한 로직을 따로 구성해야 한다는 점을 알게 되었습니다.
추후에 시간이 남게 되면 해당 기능을 구현하도록 하겠습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-31 05:13 UTC, jamessoun93 requested changes

2021-12-31 05:13 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'message' : 'EMAIL_DUPLICATE_VALUES'}, status = 400)
참고자료 첨부드릴테니 확인하시고 공부해서 어떻게 효율적으로 변경할 수 있을지 생각해보고 적용해주세요.
[ 참고자료 ](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#django.db.models.query.QuerySet.exists)

2021-12-31 05:13 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'message': 'JSONDECODE_ERROR'}, status = 404)
여기서 `404`를 사용하신 이유가 무엇일까요?

2021-12-31 05:13 UTC, jamessoun93 commented on users/views.py
> +        except KeyError:
`KeyError`는 언제 발생할까요?

2021-12-31 05:57 UTC, black2code commented on users/views.py
> +                return JsonResponse({'message' : 'EMAIL_DUPLICATE_VALUES'}, status = 400)
filter를 사용하게 되면 그 해당 값을 불러오고, exists()를 사용하면 그 값이 있는지 없는지 체크해주기 때문에 exists()를 사용하는게 더 효율적으로 생각하면 될까요?

2021-12-31 05:57 UTC, black2code commented on users/views.py
> +            return JsonResponse({'message': 'JSONDECODE_ERROR'}, status = 404)
404 에러는 서버가 요청한 페이지를 찾을 수 없다라는 뜻인데, JsonDecodeError는 Json 형식이 아닌 다른 형식으로 서버에 요청했을 경우를 발생합니다... 404 에러는 잘못 사용했네요, 400 에러로 하면 될까요?

2021-12-31 05:57 UTC, black2code commented on users/views.py
> +        except KeyError:
KeyError는 받아야 할 key값중 하나라도 받지 못하면 에러를 발생합니다.

2021-12-31 07:07 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'message' : 'EMAIL_DUPLICATE_VALUES'}, status = 400)
넵!

2021-12-31 07:07 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'message': 'JSONDECODE_ERROR'}, status = 404)
넵!

2021-12-31 07:08 UTC, jamessoun93 commented on users/views.py
> +        except KeyError:
👍

2021-12-31 07:08 UTC, jamessoun93 commented
충돌해결해주세요!

2022-01-01 17:09 UTC, black2code commented
컨플릭트 수정 완료 했습니다.

2022-01-02 03:14 UTC, jamessoun93 commented
LGTM

2022-01-02 03:14 UTC, merged